/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

#include <stdio.h>

int isEven(int n){
    return n % 2 == 0;
}

int main(){
    int i = 1;
    int j = 1;
    int swap = 0;
    int sum = 0;
    for(j = 1; j < 4000000;){
        swap = i;
        i = j;
        j = swap + j;
        if(isEven(j)){
            printf("%d\n", j);
            sum += j;
        }
    }
    printf("The sum of the even-valued terms in the Fibonacci sequence whose values do not exceed four million is: %d\n", sum);
    return 0;
}